# The FROM instruction sets the Base Image for subsequent instructions.
# Using Nginx as Base Image
FROM maven:3.5.0-jdk-8-alpine
MAINTAINER dingdayong “dingdayong@21cn.com"

WORKDIR /project
ADD . /project


RUN mvn package -Dmaven.test.skip=true
CMD ["mvn"]