FROM java

LABEL maintainer “bankmock@daocloud.io"

COPY /project/target/bankmock-0.0.1-SNAPSHOT.jar  /usr/src/myapp/bankmock-0.0.1-SNAPSHOT.jar

WORKDIR /usr/src/myapp/

ENTRYPOINT java -jar bankmock-0.0.1-SNAPSHOT.jar